src/Entity/Messages.php
<?php

namespace App\Entity;

use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass="App\Repository\MessagesRepository")
 */
class Messages
{
    /**
     * @ORM\Id()
     * @ORM\GeneratedValue()
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $message;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $user_name;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getMessage(): ?string
    {
        return $this->message;
    }

    public function setMessage(string $message): self
    {
        $this->message = $message;

        return $this;
    }

    public function getUserName(): ?string
    {
        return $this->user_name;
    }

    public function setUserName(string $user_name): self
    {
        $this->user_name = $user_name;

        return $this;
    }
}

src/Entity/User.php
<?php

namespace App\Entity;

use Doctrine\ORM\Mapping as ORM;
use Symfony\Bridge\Doctrine\Validator\Constraints\UniqueEntity;
use Symfony\Component\Security\Core\User\UserInterface;

/**
 * @ORM\Entity(repositoryClass="App\Repository\UserRepository")
 * @UniqueEntity(fields={"name"}, message="Пользователь с таким именем уже существует")
 */
class User implements UserInterface
{
    /**
     * @ORM\Id()
     * @ORM\GeneratedValue()
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=180, unique=true)
     */
    private $name;

    /**
     * @ORM\Column(type="json")
     */
    private $roles = [];

    /**
     * @var string The hashed password
     * @ORM\Column(type="string")
     */
    private $password;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getName(): ?string
    {
        return $this->name;
    }

    public function setName(string $name): self
    {
        $this->name = $name;

        return $this;
    }

    /**
     * A visual identifier that represents this user.
     *
     * @see UserInterface
     */
    public function getUsername(): string
    {
        return (string) $this->name;
    }

    /**
     * @see UserInterface
     */
    public function getRoles(): array
    {
        $roles = $this->roles;
        // guarantee every user at least has ROLE_USER
        $roles[] = 'ROLE_USER';

        return array_unique($roles);
    }

    public function setRoles(array $roles): self
    {
        $this->roles = $roles;

        return $this;
    }

    /**
     * @see UserInterface
     */
    public function getPassword(): string
    {
        return (string) $this->password;
    }

    public function setPassword(string $password): self
    {
        $this->password = $password;

        return $this;
    }

    /**
     * @see UserInterface
     */
    public function getSalt()
    {
        // not needed when using the "bcrypt" algorithm in security.yaml
    }

    /**
     * @see UserInterface
     */
    public function eraseCredentials()
    {
        // If you store any temporary, sensitive data on the user, clear it here
        // $this->plainPassword = null;
    }
}

templates/base.html.twig
<!DOCTYPE html>
<html>
<head>
    <meta charset="UTF-8">
    <title>{% block title %}{{ title }}{% endblock %}</title>
    {% block stylesheets %}<link href="{{ asset('style/style.css') }}" rel="stylesheet" /> {% endblock %}

</head>
<body class='background'>
{% block javascripts %}<script src="{{ asset('js/lib/jquery-3.4.1.min.js') }}"></script>{% endblock %}
{% block body %}{% endblock %}
</body>
</html>

templates/index.html.twig
{% extends 'base.html.twig' %}
{% block body %}
<div class='background_blure'>
</div>
<div class='clyde_message_enther'>
    <p class='clyde_message'>
        1101000010111111110100...
        Чтобы начать выбери одно из двух !...
    </p>
</div>
<div class='form_enther'>
    <a class='enther_button' href='sign-in'>ВХОД</a>
    <a class='register_button' href='sign-up'>РЕГИСТРАЦИЯ</a>
</div>
{% endblock %}

templates/login.html.twig
{% extends 'base.html.twig' %}

{% block body %}
    <div class='background_blure'></div>
    <div class='clyde_message_login'>
        <ul class='clyde_message'>
            <a>Выбор: Активирован*(?*:%)<br><br>
                {% if error %}
                    <li class=clyde_message_info ><b>{{ error.messageKey|trans(error.messageData, 'security') }}</b></li>
                {% endif %}

        </ul>
    </div>
    <form class="autorise_box" method="post" action="sign-in">
        <a href="/"></a>
        <input type="text" name="name" id="inputName" class="form-control" required autofocus placeholder="Имя">
        <input type="password" name="password" id="inputPassword" class="form-control" required placeholder="Пароль">
        <input type="hidden" name="_csrf_token"
               value="{{ csrf_token('authenticate') }}"
        >


        <div class="remember_user">
            <label>
                <input class="checkbox" type="checkbox" name="_remember_me" > Запонить меня.
            </label>
        </div>


    <button class="btn btn-lg btn-primary" type="submit">
        Вход
    </button>
</form>
{% endblock %}

templates/register.html.twig
{% extends 'base.html.twig' %}

{% block body %}
    <script src="{{ asset('js/account/authorize.js') }}"></script>
    <div class='background_blure'></div>
    <div class='clyde_message_login'>
        <ul class='clyde_message'>
            <a>Выбор: Активирован*(?*:%)<br><br>
                <b>Введите ваши данные</b></a>
        </ul>
    </div>

    {{ form_start(registrationForm, {
        attr:{
            'class': 'register_form'
            }
        })
    }}
    <a href="/"></a>
        {{ form_row(registrationForm.name) }}
        {{ form_row(registrationForm.password) }}
        {{ form_row(registrationForm.send) }}
    {{ form_end(registrationForm) }}
{% endblock %}

templates/temp.html.twig
{% extends 'base.html.twig' %}

{% block body %}
<div> Работает </div>

    {% if app.user %}
        <div class="main_box">
            Ты с нами  {{ app.user.username }}, <a href="{{ path('app_logout') }}">Выход</a>
    {% endif %}
      <table class="table">
          <thead>
          <tr>
              <th>Id</th>
              <th>Message</th>
              <th>User_name</th>
              <th>actions</th>
          </tr>
          </thead>
          <tbody>
          {% for message in messages %}
              <tr>
                  <td>{{ message.id }}</td>
                  <td>{{ message.message }}</td>
                  <td>{{ message.userName }}</td>
                  <td>
                      <a href="{{ path('messages_show', {'id': message.id}) }}">show</a>
                      <a href="{{ path('messages_edit', {'id': message.id}) }}">edit</a>
                  </td>
              </tr>
          {% else %}
              <tr>
                  <td colspan="4">no records found</td>
              </tr>
          {% endfor %}
          </tbody>
      </table>

    </div>
{% endblock %}